from __future__ import annotations

from typing import Protocol

from quantrade_schemas.models import DataHealth, Signal


class QuanTradeRepository(Protocol):
    def save_signal(self, signal: Signal) -> None: ...

    def list_signals(self) -> list[Signal]: ...

    def save_data_health(self, health: DataHealth) -> None: ...

    def list_data_health(self) -> list[DataHealth]: ...

    def save_paper_order_result(self, result: dict[str, object]) -> None: ...

    def list_paper_positions(self) -> list[dict[str, object]]: ...

    def latest_portfolio(self) -> dict[str, object] | None: ...

    def list_journal_entries(self) -> list[dict[str, object]]: ...

    def latest_performance(self) -> dict[str, object] | None: ...

